workflows:
  android-free:
    name: Smart Farmer Android Free Build
    max_build_duration: 120
    instance_type: mac_pro  # <-- THIS ONE IS FREE
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    cache:
      cache_paths:
        - $HOME/.pub-cache
